# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yamcs/api/httpbody.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'yamcs/api/httpbody.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18yamcs/api/httpbody.proto\x12\tyamcs.api\"\xa6\x01\n\x08HttpBody\x12\x14\n\x0c\x63ontent_type\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x33\n\x08metadata\x18\x04 \x03(\x0b\x32!.yamcs.api.HttpBody.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42 \n\rorg.yamcs.apiB\rHttpBodyProtoP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yamcs.api.httpbody_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rorg.yamcs.apiB\rHttpBodyProtoP\001'
  _globals['_HTTPBODY_METADATAENTRY']._loaded_options = None
  _globals['_HTTPBODY_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_HTTPBODY']._serialized_start=40
  _globals['_HTTPBODY']._serialized_end=206
  _globals['_HTTPBODY_METADATAENTRY']._serialized_start=159
  _globals['_HTTPBODY_METADATAENTRY']._serialized_end=206
# @@protoc_insertion_point(module_scope)
