# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yamcs/protobuf/tse/tse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yamcs.protobuf import yamcs_pb2 as yamcs_dot_protobuf_dot_yamcs__pb2
from yamcs.protobuf.commanding import commanding_pb2 as yamcs_dot_protobuf_dot_commanding_dot_commanding__pb2
from yamcs.protobuf.pvalue import pvalue_pb2 as yamcs_dot_protobuf_dot_pvalue_dot_pvalue__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yamcs/protobuf/tse/tse.proto',
  package='yamcs.protobuf.tse',
  syntax='proto2',
  serialized_options=_b('\n\022org.yamcs.protobuf'),
  serialized_pb=_b('\n\x1cyamcs/protobuf/tse/tse.proto\x12\x12yamcs.protobuf.tse\x1a\x1ayamcs/protobuf/yamcs.proto\x1a*yamcs/protobuf/commanding/commanding.proto\x1a\"yamcs/protobuf/pvalue/pvalue.proto\"\x9b\x03\n\nTseCommand\x12\x30\n\x02id\x18\x06 \x01(\x0b\x32$.yamcs.protobuf.commanding.CommandId\x12\x12\n\ninstrument\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x01(\t\x12L\n\x0f\x61rgumentMapping\x18\x04 \x03(\x0b\x32\x33.yamcs.protobuf.tse.TseCommand.ArgumentMappingEntry\x12N\n\x10parameterMapping\x18\x05 \x03(\x0b\x32\x34.yamcs.protobuf.tse.TseCommand.ParameterMappingEntry\x1aM\n\x14\x41rgumentMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.yamcs.protobuf.Value:\x02\x38\x01\x1a\x37\n\x15ParameterMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"m\n\x12TseCommandResponse\x12\x30\n\x02id\x18\x01 \x01(\x0b\x32$.yamcs.protobuf.commanding.CommandId\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x14\n\x0c\x65rrorMessage\x18\x03 \x01(\t\"\x93\x01\n\x13TseCommanderMessage\x12?\n\x0f\x63ommandResponse\x18\x01 \x01(\x0b\x32&.yamcs.protobuf.tse.TseCommandResponse\x12;\n\rparameterData\x18\x02 \x01(\x0b\x32$.yamcs.protobuf.pvalue.ParameterDataB\x14\n\x12org.yamcs.protobuf')
  ,
  dependencies=[yamcs_dot_protobuf_dot_yamcs__pb2.DESCRIPTOR,yamcs_dot_protobuf_dot_commanding_dot_commanding__pb2.DESCRIPTOR,yamcs_dot_protobuf_dot_pvalue_dot_pvalue__pb2.DESCRIPTOR,])




_TSECOMMAND_ARGUMENTMAPPINGENTRY = _descriptor.Descriptor(
  name='ArgumentMappingEntry',
  full_name='yamcs.protobuf.tse.TseCommand.ArgumentMappingEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yamcs.protobuf.tse.TseCommand.ArgumentMappingEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='yamcs.protobuf.tse.TseCommand.ArgumentMappingEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=515,
)

_TSECOMMAND_PARAMETERMAPPINGENTRY = _descriptor.Descriptor(
  name='ParameterMappingEntry',
  full_name='yamcs.protobuf.tse.TseCommand.ParameterMappingEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yamcs.protobuf.tse.TseCommand.ParameterMappingEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='yamcs.protobuf.tse.TseCommand.ParameterMappingEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=572,
)

_TSECOMMAND = _descriptor.Descriptor(
  name='TseCommand',
  full_name='yamcs.protobuf.tse.TseCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='yamcs.protobuf.tse.TseCommand.id', index=0,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrument', full_name='yamcs.protobuf.tse.TseCommand.instrument', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='yamcs.protobuf.tse.TseCommand.command', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='yamcs.protobuf.tse.TseCommand.response', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='argumentMapping', full_name='yamcs.protobuf.tse.TseCommand.argumentMapping', index=4,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameterMapping', full_name='yamcs.protobuf.tse.TseCommand.parameterMapping', index=5,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TSECOMMAND_ARGUMENTMAPPINGENTRY, _TSECOMMAND_PARAMETERMAPPINGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=572,
)


_TSECOMMANDRESPONSE = _descriptor.Descriptor(
  name='TseCommandResponse',
  full_name='yamcs.protobuf.tse.TseCommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='yamcs.protobuf.tse.TseCommandResponse.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='yamcs.protobuf.tse.TseCommandResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='yamcs.protobuf.tse.TseCommandResponse.errorMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=683,
)


_TSECOMMANDERMESSAGE = _descriptor.Descriptor(
  name='TseCommanderMessage',
  full_name='yamcs.protobuf.tse.TseCommanderMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandResponse', full_name='yamcs.protobuf.tse.TseCommanderMessage.commandResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameterData', full_name='yamcs.protobuf.tse.TseCommanderMessage.parameterData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=833,
)

_TSECOMMAND_ARGUMENTMAPPINGENTRY.fields_by_name['value'].message_type = yamcs_dot_protobuf_dot_yamcs__pb2._VALUE
_TSECOMMAND_ARGUMENTMAPPINGENTRY.containing_type = _TSECOMMAND
_TSECOMMAND_PARAMETERMAPPINGENTRY.containing_type = _TSECOMMAND
_TSECOMMAND.fields_by_name['id'].message_type = yamcs_dot_protobuf_dot_commanding_dot_commanding__pb2._COMMANDID
_TSECOMMAND.fields_by_name['argumentMapping'].message_type = _TSECOMMAND_ARGUMENTMAPPINGENTRY
_TSECOMMAND.fields_by_name['parameterMapping'].message_type = _TSECOMMAND_PARAMETERMAPPINGENTRY
_TSECOMMANDRESPONSE.fields_by_name['id'].message_type = yamcs_dot_protobuf_dot_commanding_dot_commanding__pb2._COMMANDID
_TSECOMMANDERMESSAGE.fields_by_name['commandResponse'].message_type = _TSECOMMANDRESPONSE
_TSECOMMANDERMESSAGE.fields_by_name['parameterData'].message_type = yamcs_dot_protobuf_dot_pvalue_dot_pvalue__pb2._PARAMETERDATA
DESCRIPTOR.message_types_by_name['TseCommand'] = _TSECOMMAND
DESCRIPTOR.message_types_by_name['TseCommandResponse'] = _TSECOMMANDRESPONSE
DESCRIPTOR.message_types_by_name['TseCommanderMessage'] = _TSECOMMANDERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TseCommand = _reflection.GeneratedProtocolMessageType('TseCommand', (_message.Message,), dict(

  ArgumentMappingEntry = _reflection.GeneratedProtocolMessageType('ArgumentMappingEntry', (_message.Message,), dict(
    DESCRIPTOR = _TSECOMMAND_ARGUMENTMAPPINGENTRY,
    __module__ = 'yamcs.protobuf.tse.tse_pb2'
    # @@protoc_insertion_point(class_scope:yamcs.protobuf.tse.TseCommand.ArgumentMappingEntry)
    ))
  ,

  ParameterMappingEntry = _reflection.GeneratedProtocolMessageType('ParameterMappingEntry', (_message.Message,), dict(
    DESCRIPTOR = _TSECOMMAND_PARAMETERMAPPINGENTRY,
    __module__ = 'yamcs.protobuf.tse.tse_pb2'
    # @@protoc_insertion_point(class_scope:yamcs.protobuf.tse.TseCommand.ParameterMappingEntry)
    ))
  ,
  DESCRIPTOR = _TSECOMMAND,
  __module__ = 'yamcs.protobuf.tse.tse_pb2'
  # @@protoc_insertion_point(class_scope:yamcs.protobuf.tse.TseCommand)
  ))
_sym_db.RegisterMessage(TseCommand)
_sym_db.RegisterMessage(TseCommand.ArgumentMappingEntry)
_sym_db.RegisterMessage(TseCommand.ParameterMappingEntry)

TseCommandResponse = _reflection.GeneratedProtocolMessageType('TseCommandResponse', (_message.Message,), dict(
  DESCRIPTOR = _TSECOMMANDRESPONSE,
  __module__ = 'yamcs.protobuf.tse.tse_pb2'
  # @@protoc_insertion_point(class_scope:yamcs.protobuf.tse.TseCommandResponse)
  ))
_sym_db.RegisterMessage(TseCommandResponse)

TseCommanderMessage = _reflection.GeneratedProtocolMessageType('TseCommanderMessage', (_message.Message,), dict(
  DESCRIPTOR = _TSECOMMANDERMESSAGE,
  __module__ = 'yamcs.protobuf.tse.tse_pb2'
  # @@protoc_insertion_point(class_scope:yamcs.protobuf.tse.TseCommanderMessage)
  ))
_sym_db.RegisterMessage(TseCommanderMessage)


DESCRIPTOR._options = None
_TSECOMMAND_ARGUMENTMAPPINGENTRY._options = None
_TSECOMMAND_PARAMETERMAPPINGENTRY._options = None
# @@protoc_insertion_point(module_scope)
